Update OptiX to 7.6
DeclanRussell/NvidiaAIDenoiser pull request #27
Opened 2022-11-28 11:17 UTC by Vadim-Karpenko

I've used OptixDenoiserAlphaMode instead of plain int value because otherwise, it throws an error during the compilation. Not sure if this is the right thing to do, but everything works fine for me after I made this change, so I decided to create a pull request so you can check this out and decide if this is worth merging.

2022-11-28 12:10 UTC, DeclanRussell requested changes
Thanks for the PR! It looks like this was a new change in OptiX 7.6.0. Would be good to have this ifdefed like so, such that it compiles for both versions.

2022-11-28 12:10 UTC, DeclanRussell commented on src/main.cpp
> +    denoiser_params.denoiseAlpha = OptixDenoiserAlphaMode(0);
```suggestion
#if OPTIX_VERSION >= 70600
    denoiser_params.denoiseAlpha = OptixDenoiserAlphaMode(0);
#else
    denoiser_params.denoiseAlpha = 0;
#endif
```

2022-11-28 12:21 UTC, Vadim-Karpenko commented
Great idea! 
I completely forgot about the backward compatibility of older SDKs

2022-11-28 14:28 UTC, DeclanRussell commented
Looks great, thanks a bunch! 😄

2022-11-28 14:29 UTC, merged

2022-11-29 04:29 UTC, Vadim-Karpenko commented
Here's a new version I've compiled for myself on Windows 10, x64. I want to share it here as well so you can use it for creating a new release if you don't have a dev environment on your hands right now.
[Denoiser_v.2.5_unofficial.zip](https://github.com/DeclanRussell/NvidiaAIDenoiser/files/10109721/Denoiser_v.2.5_unofficial.zip)

2023-01-11 04:55 UTC, mojo-jojo-7 commented
@Vadim-Karpenko thank you for this! Wanted to try temporal denoising but did not have the technical know-how to build from source myself.

It would be cool if a (much awaited) release is pushed with the new binaries, updated readme and everything.

2023-01-15 14:21 UTC, ChristopheMoreau commented
> @Vadim-Karpenko thank you for this! Wanted to try temporal denoising but did not have the technical know-how to build from source myself.
> 
> It would be cool if a (much awaited) release is pushed with the new binaries, updated readme and everything.

+1 🙏